FROM node:8.7.0
LABEL maintainer "Guild Engineering <engineering@guildeducation.com>"

RUN curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > /usr/local/bin/cc-test-reporter && \
    chmod +x /usr/local/bin/cc-test-reporter
